software:
  hickit: /share/home/ychi/software/hickit/hickit
  k8: /share/home/ychi/software/hickit/k8
  js: /share/home/ychi/software/hickit/hickit.js
  hires: /share/home/ychi/software/hires_utils
reference:
  bwa: /share/Data/public/ref_genome/ara_ref_embl/bwamem2_index/genome.fa
  star: /share/Data/public/ref_genome/ara_ref_embl/star_index
  annotation: /share/Data/public/ref_genome/ara_ref_embl/Rawdata/Arabidopsis_thaliana.TAIR10.52.gtf

cpu:
  bwa: 8
  split: 8
  clean1: 8
  clean2: 8
  clean3: 8
  cut_r2: 8

# change every time
ana_home: /shareb/ychi/repo/ara_test