software:
  hickit: /share/home/ychi/software/hickit/hickit
  k8: /share/home/ychi/software/hickit/k8
  js: /share/home/ychi/software/hickit/hickit.js
  hires: /share/home/ychi/dev/hires_utils
reference:
  # for each species, regist every entry in reference
  bwa: 
    hg19: /share/Data/ychi/genome/GRCh37d5/bwa_mem2_index/genome.fa
    mm10_B6_CAST: /share/home/ychi/data/genome/GRCm38/bwa_mem2_index/genome.fa
    mm10_B6_DBA2: /share/home/ychi/data/genome/GRCm38/bwa_mem2_index/genome.fa
    mm10_B6: /share/home/ychi/data/genome/GRCm38/bwa_mem2_index/genome.fa
    mm10_129_CAST: /share/home/ychi/data/genome/GRCm38/bwa_mem2_index/genome.fa
    ara: /share/Data/public/ref_genome/ara_ref_embl/bwamem2_index/genome.fa
  # if doesn't have snp.tsv file, give a nonsense 4 col tsv
  snp: 
    hg19: /share/Data/ychi/genome/GRCh37d5/GM12878.hg19.snp.tsv
    mm10_B6_CAST: /share/home/ychi/data/genome/GRCm38/phased.B6_CAST.chr.vcf.tsv
    mm10_B6_DBA2: /share/home/ychi/data/genome/mouse_snp/B6_DBA2/B6_DBA2.phased.snp.withchr.tsv
    mm10_129_CAST: /share/home/ychi/data/genome/mouse_snp/129_CAST/129_CAST.phased.snp.withchr.tsv
    mm10_B6: /share/home/ychi/data/genome/mouse_snp/B6_DBA2/B6_DBA2.phased.snp.withchr.tsv
  par:
    hg19: /share/Data/ychi/genome/GRCh37d5/hg19.PAR.bed
    mm10_B6_CAST: /share/home/ychi/data/genome/GRCm38/GRCm38.PAR.bed
    mm10_B6_DBA2: /share/home/ychi/data/genome/GRCm38/GRCm38.PAR.bed
    mm10_129_CAST: /share/home/ychi/data/genome/GRCm38/GRCm38.PAR.bed
    mm10_B6: /share/home/ychi/data/genome/GRCm38/GRCm38.PAR.bed
  star:
    hg19: /share/Data/ychi/genome/GRCh37d5/star_index
    mm10_B6_CAST: /share/home/ychi/data/genome/GRCm38/star_index
    mm10_B6_DBA2: /share/home/ychi/data/genome/GRCm38/star_index
    mm10_B6: /share/home/ychi/data/genome/GRCm38/star_index
    mm10_129_CAST: /share/home/ychi/data/genome/GRCm38/star_index
    ara: /share/Data/public/ref_genome/ara_ref_embl/star_index
  annotation: 
    hg19: /share/Data/ychi/genome/GRCh37d5/raw/gencode.v19.annotation.gtf
    mm10_B6_CAST: /share/home/ychi/data/genome/GRCm38/raw/gencode.vM25.annotation.gtf
    mm10_B6_DBA2: /share/home/ychi/data/genome/GRCm38/raw/gencode.vM25.annotation.gtf
    mm10_B6: /share/home/ychi/data/genome/GRCm38/raw/gencode.vM25.annotation.gtf
    mm10_129_CAST: /share/home/ychi/data/genome/GRCm38/raw/gencode.vM25.annotation.gtf
    ara: /share/Data/public/ref_genome/ara_ref_embl/Rawdata/Arabidopsis_thaliana.TAIR10.52.gtf
cpu:
  bwa: 8
  split: 8
  sam2seg: 4
  clean1: 8
  clean2: 8
  clean3: 8
  cut_r2: 8
  cut_r3: 8
  sortBAM: 8

# change every time
## global_mode: ploidy_sex_snp_imputation_build
## ploidy: 1C, 2C
## sex: lY, hY (means low Y, high Y)
## snp: SNP, other
## imputation: c1i, c12i, c123i
## build: c1b, c12b, c123b， Ib, Icb
global_mode: 1C__SNP_c123i_c12b
global_ref: mm10_B6_CAST
ana_home: /shareb/ychi/repo/PROJECT
sample_table: /shareb/ychi/ana/PROJECT/config/sample_table.csv