software:
  hickit: /share/home/ychi/software/hickit/hickit
  k8: /share/home/ychi/software/hickit/k8
  js: /share/home/ychi/software/hickit/hickit.js
  hires: /share/home/ychi/software/hires-utils/hires.py
  hires_index: /share/home/ychi/software/hires-utils/bin_10k_FULL_index
  dip-c: /share/home/ychi/software/dip-c/dip-c
  pairs2con: /share/home/ychi/software/dip-c/scripts/hickit_pairs_to_con.sh
  impute2con: /share/home/ychi/software/dip-c/scripts/hickit_impute_pairs_to_con.sh
reference:
  bwa: /share/home/ychi/software/bwa_index/GRCh38
  snp: /share/home/ychi/software/snp_file/gm12878/NA12878.phased_SNP.tsv
  par: /share/home/ychi/software/GRCh38.chrY.PAR.bed
  star: /share/home/ychi/software/star_index
  annotation: /share/home/ychi/software/gencode.v33.primary_assembly.annotation.gtf
sex: female
logs: /share/Data/ychi/repo/300s1/logs
dirs:
  #for all
  raw: /share/Data/ychi/raw
  dna: /share/Data/ychi/repo/300s1/dna
  rna: /share/Data/ychi/repo/300s1/rna
  rna_c: /share/Data/ychi/repo/300s1/rna_c
  umi: /share/Data/ychi/repo/300s1/umi
  umi_cell: /share/Data/ychi/repo/300s1/umi_cell
  sam: /share/Data/ychi/repo/300s1/sam
  seg: /share/Data/ychi/repo/300s1/seg
  pairs_0: /share/Data/ychi/repo/300s1/pairs_0
  pairs_c1: /share/Data/ychi/repo/300s1/pairs_c1
  pairs_c12: /share/Data/ychi/repo/300s1/pairs_c12
  pairs_c123: /share/Data/ychi/repo/300s1/pairs_c123
  impute: /share/Data/ychi/repo/300s1/impute
  3dg: /share/Data/ychi/repo/300s1/3dg
  #for part
  merged_rna: /share/Data/ychi/repo/300s1/merged_rna
  star_mapped: /share/Data/ychi/repo/300s1/star_mapped
  count_gene: /share/Data/ychi/repo/300s1/count_gene
  count_exon: /share/Data/ychi/repo/300s1/count_exon
  count_matrix: /share/Data/ychi/repo/300s1/count_matrix

