software:
  hickit: /share/home/ychi/software/hickit/hickit
  k8: /share/home/ychi/software/hickit/k8
  js: /share/home/ychi/software/hickit/hickit.js
  hires: /share/home/ychi/software/hires-utils/hires.py
  hires_index: /share/home/ychi/software/hires-utils/bin_10k_FULL_index
  dip-c: /share/home/ychi/software/dip-c/dip-c
  pairs2con: /share/home/ychi/software/dip-c/scripts/hickit_pairs_to_con.sh
  impute2con: /share/home/ychi/software/dip-c/scripts/hickit_impute_pairs_to_con.sh
  rescale: "/share/home/ychi/software/dip-c/scripts/hickit_3dg_to_3dg_rescale_unit.sh"
  color_file: "/share/Data/ychi/genome/GRCh38.chr.fem.txt"
reference:
  bwa: /share/Data/ychi/genome/GRCh37d5/bwa_mem2_index
  snp: /share/Data/ychi/genome/GRCh37d5/GM12878.hg19.snp.tsv
  par: /share/home/ychi/genome/GRCh37d5/hg19.PAR.bed
  star: /share/home/ychi/software/star_index
  annotation: /share/home/ychi/software/gencode.v33.primary_assembly.annotation.gtf

cpu:
  bwa: 8
  split: 8
  clean1: 8
  clean2: 8
  clean3: 8
  cut_r2: 8

# change every time
snp: using #using or anything else
sex: female
ana_home: /share/Data/ychi/repo/test_bubble_flow
